# Generated by Django 3.0.10 on 2021-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('acp_id', models.AutoField(primary_key=True)),
                ('acp_prc_id', models.IntegerField()),
                ('acp_plt_id', models.IntegerField()),
                ('acp_tipo', models.CharField(max_length=1000)),
                ('acp_esp', models.CharField(max_length=1000)),
                ('acp_data_cumprimento', models.CharField(max_length=1000)),
                ('acp_data_evento', models.CharField(max_length=1000)),
                ('acp_data_prazo', models.CharField(max_length=1000)),
                ('acp_data_cadastro', models.CharField(max_length=1000)),
                ('acp_data', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'acompanhamento',
            },
        ),
    ]
